name: Check PR head

on:
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  check-head:
    name: Check PR head on release
    runs-on: ubuntu-18.04
    env:
      PR_HEAD_EXPECTED: parzh:develop
      PR_HEAD: ${{ github.event.pull_request.head.label }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - run: python scripts/check-pr-head.py
