name: Check SemVer label

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-label:
    name: Check SemVer label
    runs-on: ubuntu-18.04
    env:
      PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
            python-version: '3.8'

      - run: python scripts/check-labels.py
