name: Check version match

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - package*.json

jobs:
  check-version-match:
    name: Check versions in package*.json files match
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Ensure versions in package.json and package-lock.json match
        run: node -pe "process.exit(require('./package.json').version !== require('./package-lock.json').version);"
