name: Check SemVer label

on:
  pull_request:
    branches:
      - develop

jobs:
  check-label:
    name: Check SemVer label
    runs-on: ubuntu-18.04
    if: github.event.action == 'opened' || github.event.action == 'labeled' || github.event.action == 'unlabeled'
    env:
      PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}

    steps:
      - uses: actions/checkout@v2

      - run: |2
          node -pe '
            const labels = JSON.parse(process.env.PR_LABELS);
            const [ label, ...other ] = labels.filter((label) => label.startsWith("Change: "));

            if (other.length > 0)
              throw new Error(`Expected exactly one "Change: ***" label`);

            if (!label)
              throw new Error(`No "Change: ***" labels found`);

            const [ , change ] = label;

            console.log(`SemVer change is ${ change }`);
          '
