name: Test changes

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

  unit-tests:
    name: Run unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm test

  lint:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run lint
