name: Test changes

on:
  - push
  - pull_request

jobs:
  build:
    name: Run build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm test
